version: '3.8'

services:

  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  app:
    build: .
    command: >
      bash -c "rm -f tmp/pids/server.pid && 
      # bundle exec rails server --port=3000 --binding='0.0.0.0'"
      bundle exec rdebug-ide --debug --host 0.0.0.0 --port 1234 -- rails s -p 3000 -b 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "1234:1234"
      - "3000:3000"
      - "26162:26162"
    depends_on:
      - db
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
