version: '3.8'

services:

  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "1234:1234"
      - "3000:3000"
      - "26162:26162"
    depends_on:
      - db
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - RDEBUG_IDE
