default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: <%= ENV.fetch('POSTGRES_USER', 'postgres') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', 'password') %>
  pool: 5

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test
